AWSTemplateFormatVersion: "2010-09-09"
Description: ETL batch task that loads S3 → PostGIS.

Parameters:
  ProjectName:
    Type: String
    Default: geo
  Environment:
    Type: String
    Default: prod
  EtlImageUri:
    Type: String

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: {Service: ecs-tasks.amazonaws.com}
            Action: ["sts:AssumeRole"]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: {Service: ecs-tasks.amazonaws.com}
            Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: s3-read
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ["s3:GetObject"]
                Resource: !Sub "arn:aws:s3:::${ProjectName}-${Environment}-raw-${AWS::AccountId}/*"

  EtlTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ProjectName}-etl"
      Cpu: "1024"
      Memory: "2048"
      NetworkMode: awsvpc
      RequiresCompatibilities: ["FARGATE"]
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: etl
          Image: !Ref EtlImageUri
          Environment:
            - Name: DB_HOST
              Value: !ImportValue Fn::Sub: "${ProjectName}-${Environment}-PostgresEndpoint"
            - Name: S3_BUCKET
              Value: !ImportValue Fn::Sub: "${ProjectName}-${Environment}-S3RawBucket"
          Essential: true

Outputs:
  EtlTaskDefArn:
    Value: !Ref EtlTaskDefinition
    Export:
      Name: !Sub "${ProjectName}-${Environment}-EtlTaskDefArn"
